# sass 처럼 tab(들여쓰기)이 종속관계를 나타 냄
# 한글깨짐 방지하려면 인텔리제이 하단에 ISO-8859-1 를 UTF-8로 변경하세요
spring:
  application:
    name: l04_spring_jpa
  datasource:
    username: ${mysql.user}
    password: ${mysql.pw}
    url: jdbc:mysql://localhost:3306/employees
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 5555

